### ISSUE TITLE
Handle Errors Better

### ISSUE THREAD

**Issue by blainsmith** [oddnetworks/seneca-odd-auth#1]
Currently throwing stack traces and filling up logs.

```
2016-03-07T20:18:03.724Z 6418857cdloi/1457381839270/15/- ERROR	act	device-auth	OUT		cmd:issueAccessToken,role:device-auth	69	{role:device-auth,cmd:issueAccessToken,organizationID:levintv,deviceType:ROKU_ROKU,deviceCode:dupym3OyTXbN6VvgY	ENTRY	(h81tc)	-	seneca: Action cmd:issueAccessToken,role:device-auth failed: deviceUserProfileID for deviceCodeKey not found.	act_execute	{id:uwsycsuhx5fp/1b98qess9at3,gate:false,ungate:false,desc:null,time:{start:1457381883688,end:1457381883721},me	ClientUserInfoError
2016-03-07T20:18:03.726285+00:00 app[web.2]:     at Object.<anonymous> (/app/node_modules/@oddnetworks/seneca-odd-auth/lib/odd_errors.js:24:33)
2016-03-07T20:18:03.726286+00:00 app[web.2]:     at Module._compile (module.js:435:26)
2016-03-07T20:18:03.726287+00:00 app[web.2]:     at Object.Module._extensions..js (module.js:442:10)
2016-03-07T20:18:03.726288+00:00 app[web.2]:     at Module.load (module.js:356:32)
2016-03-07T20:18:03.726288+00:00 app[web.2]:     at Function.Module._load (module.js:313:12)
2016-03-07T20:18:03.726289+00:00 app[web.2]:     at Function._load (/app/node_modules/opbeat/lib/instrumentation/index.js:35:39)
2016-03-07T20:18:03.726290+00:00 app[web.2]:     at Module.require (module.js:366:17)
2016-03-07T20:18:03.726290+00:00 app[web.2]:     at require (module.js:385:17)
2016-03-07T20:18:03.726291+00:00 app[web.2]:     at Object.<anonymous> (/app/node_modules/@oddnetworks/seneca-odd-auth/actions/device-auth.js:7:17)
2016-03-07T20:18:03.726292+00:00 app[web.2]:     at Module._compile (module.js:435:26)
2016-03-07T20:18:03.726292+00:00 app[web.2]:     at Object.Module._extensions..js (module.js:442:10)
2016-03-07T20:18:03.726307+00:00 app[web.2]:     at Module.load (module.js:356:32)
2016-03-07T20:18:03.726308+00:00 app[web.2]:     at Function.Module._load (module.js:313:12)
2016-03-07T20:18:03.726308+00:00 app[web.2]:     at Function._load (/app/node_modules/opbeat/lib/instrumentation/index.js:35:39)
2016-03-07T20:18:03.726309+00:00 app[web.2]:     at Module.require (module.js:366:17)
2016-03-07T20:18:03.726312+00:00 app[web.2]:     at require (module.js:385:17)
2016-03-07T20:18:03.726313+00:00 app[web.2]:     at Seneca.module.exports (/app/node_modules/@oddnetworks/seneca-odd-auth/odd-device-auth.js:12:2)
2016-03-07T20:18:03.726314+00:00 app[web.2]:     at define_plugin (/app/node_modules/seneca/lib/plugins.js:335:26)
2016-03-07T20:18:03.726314+00:00 app[web.2]:     at Seneca.plugin_definition (/app/node_modules/seneca/lib/plugins.js:62:16)
2016-03-07T20:18:03.726315+00:00 app[web.2]:     at /app/node_modules/seneca/seneca.js:1134:22
2016-03-07T20:18:03.726316+00:00 app[web.2]:     at act_param_check (/app/node_modules/seneca/seneca.js:1478:17)
2016-03-07T20:18:03.726316+00:00 app[web.2]:     at Object.execute_action [as fn] (/app/node_modules/seneca/seneca.js:1078:7)
2016-03-07T20:18:03.726317+00:00 app[web.2]:     at Immediate.<anonymous> (/app/node_modules/seneca/node_modules/gate-executor/gate-executor.js:135:14)
2016-03-07T20:18:03.726318+00:00 app[web.2]:     at Immediate.instrumented (/app/node_modules/opbeat/lib/instrumentation/async-hooks.js:19:23)
2016-03-07T20:18:03.726319+00:00 app[web.2]:     at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by tquackenbush** [comment]
https://github.com/oddnetworks/seneca-odd-auth/pull/9

Returns null err/resp for the 404 errors at least.
device-api should be updated to check for null resp before pushing this live.

**Comment by clarkefoley** [comment]
This needs to be re-included and pushed to prod, thanks!
